package projetException;

import java.util.Scanner;
import java.util.*;

public class Test {

	public static void main(String[] args) {
		// test1();
		// test2();
		// test3();
		// test4();
		// test5();
		test6();

	}
	
	static void testdiv2() {
		Scanner sc = new Scanner(System.in);

		try {
			System.out.println("nb1");
			int nb1 = sc.nextInt();
			System.out.println("nb2");
			int nb2 = sc.nextInt();
			int res = Traitement.div(nb1, nb2);
			System.out.println(res);
		} catch (ArithmeticException e) { // catch pour gérer les erreur
											// mathématique div par zéro
			System.out.println("division par zéro");
			System.out.println(e.getMessage());
			System.out.println(e.toString());
		} catch (InputMismatchException e) { // catch pour gérer l'erreur de
												// saisie
			System.out.println("erreur de saisie");
		} catch (RuntimeException e) { // catch pour gérer l'erreur de saisie
			System.out.println("runtime par zéro");
		} catch (Exception e) { // catch pour gérer les erreurs générales
			System.out.println("erreur incorrect");
		}
		System.out.println("fin du programme");
		sc.close();

	}

	static void test6() {
		Scanner sc = new Scanner(System.in);

		try {
			System.out.println("nb1");
			int nb1 = sc.nextInt();
			System.out.println("nb2");
			int nb2 = sc.nextInt();
			double res = Traitement.div(nb1, nb2);
			System.out.println(res);

			System.out.println("div 2 : nb1");
			int nb3 = sc.nextInt();
			System.out.println("div 2 : nb2");
			int nb4 = sc.nextInt();
			double res2 = Traitement.calcul(nb3, nb4);
			System.out.println(res2);

		} catch (ArithmeticException e) { // catch pour gérer les erreur
											// mathématique div par zéro
			System.out.println("division par zéro");
			System.out.println(e.getMessage());
			System.out.println(e.toString());
		} catch (InputMismatchException e) { // catch pour gérer l'erreur de
												// saisie
			System.out.println("erreur de saisie");
		} catch (RuntimeException e) { // catch pour gérer l'erreur de saisie
			System.out.println("runtime par zéro");
		} catch (Exception e) { // catch pour gérer les erreurs générales
			System.out.println("erreur incorrect");
		}
		System.out.println("fin du programme");
		sc.close();

	}

	static void testdiv() {
		Scanner sc = new Scanner(System.in);

		try {
			System.out.println("nb1");
			int nb1 = sc.nextInt();
			System.out.println("nb2");
			int nb2 = sc.nextInt();
			int res = Traitement.div(nb1, nb2);
			System.out.println(res);
		} catch (ArithmeticException e) { // catch pour gérer les erreur
											// mathématique div par zéro
			System.out.println("division par zéro");
			System.out.println(e.getMessage());
			System.out.println(e.toString());
		} catch (InputMismatchException e) { // catch pour gérer l'erreur de
												// saisie
			System.out.println("erreur de saisie");
		} catch (RuntimeException e) { // catch pour gérer l'erreur de saisie
			System.out.println("runtime par zéro");
		} catch (Exception e) { // catch pour gérer les erreurs générales
			System.out.println("erreur incorrect");
		}
		System.out.println("fin du programme");
		sc.close();

	}

	static void test4() { // gérer l'erreur avec le bloc try et catch
							// (encapsulation pour éviter le plantage !!)
		Scanner sc = new Scanner(System.in);
		System.out.println("avant");
		System.out.println("saisir chiffre dans une chaine");
		String saisie = sc.nextLine();
		try {
			int res = Integer.parseInt(saisie);
			res++;
			System.out.println("res++ = " + res);
		} catch (Exception e) {
			System.out.println("exception gérée");
		} finally {
			System.out.println("dans le finally");
		}
		// System.out.println("après");

	}

	static void test3() { // out of band (tableau petit comparé notre demande)
		int[] tab = { 1, 5, 8 };
		System.out.println(tab[3]);

	}

	static void test2() { // division par 0 !
		int a = 10;
		int b = 0;
		double c = a / b;
		System.out.println(c);

	}

	static void test1() {
		String str = "2a";
		int a = Integer.parseInt(str);
		System.out.println(a);

	}

}
